// ★ 듣는 자리를 다는 명령 이름이 여러 개다. Tauri 쪽 코드가 이렇게 부른다.
//
//   register_listener   먼저 부른다
//   registerListener    안 되면 이걸로 물러선다
//   remove_listener     놓을 때는 늘 이것이다
//   [확인: @tauri-apps/api/core.js 141·157·166줄]
//
//   권한 이름은 여기 적은 글자에서 만들어지는데 규칙이 있다.
//   밑줄은 줄표로 바뀌고, 낙타등은 그대로 남는다.
//     register_listener  →  allow-register-listener
//     registerListener   →  allow-registerListener
//   permissions/autogenerated/commands/ 를 열어 보면 확인할 수 있다.
const COMMANDS: &[&str] = &[
  "pick",
  "register_listener",
  "registerListener",
  "remove_listener",
];

fn main() {
  tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
